-- Add missing apartment tomb plots to the database (CORRECTED FORMAT)
-- This script adds individual tomb plots for apartment sections with the correct format

-- Apartment 1 - All levels (1a, 1b, 1c, 1d, 1e, 1f, 1g, 1h for each level)
INSERT INTO plots (plot_id, section, level, plot_number, status, occupant_name, age, cause_of_death, religion, family_name, next_of_kin, contact_number, date_of_interment, notes) VALUES
('apartment-1-1a', 'apartment-1', 1, '1A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-1b', 'apartment-1', 1, '1B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-1c', 'apartment-1', 1, '1C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-1d', 'apartment-1', 1, '1D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-1e', 'apartment-1', 1, '1E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-1f', 'apartment-1', 1, '1F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-1g', 'apartment-1', 1, '1G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-1h', 'apartment-1', 1, '1H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2a', 'apartment-1', 2, '2A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2b', 'apartment-1', 2, '2B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2c', 'apartment-1', 2, '2C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2d', 'apartment-1', 2, '2D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2e', 'apartment-1', 2, '2E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2f', 'apartment-1', 2, '2F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2g', 'apartment-1', 2, '2G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-2h', 'apartment-1', 2, '2H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3a', 'apartment-1', 3, '3A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3b', 'apartment-1', 3, '3B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3c', 'apartment-1', 3, '3C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3d', 'apartment-1', 3, '3D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3e', 'apartment-1', 3, '3E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3f', 'apartment-1', 3, '3F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3g', 'apartment-1', 3, '3G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-1-3h', 'apartment-1', 3, '3H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');

-- Apartment 2 - All levels
INSERT INTO plots (plot_id, section, level, plot_number, status, occupant_name, age, cause_of_death, religion, family_name, next_of_kin, contact_number, date_of_interment, notes) VALUES
('apartment-2-1a', 'apartment-2', 1, '1A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-1b', 'apartment-2', 1, '1B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-1c', 'apartment-2', 1, '1C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-1d', 'apartment-2', 1, '1D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-1e', 'apartment-2', 1, '1E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-1f', 'apartment-2', 1, '1F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-1g', 'apartment-2', 1, '1G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-1h', 'apartment-2', 1, '1H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2a', 'apartment-2', 2, '2A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2b', 'apartment-2', 2, '2B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2c', 'apartment-2', 2, '2C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2d', 'apartment-2', 2, '2D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2e', 'apartment-2', 2, '2E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2f', 'apartment-2', 2, '2F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2g', 'apartment-2', 2, '2G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-2h', 'apartment-2', 2, '2H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3a', 'apartment-2', 3, '3A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3b', 'apartment-2', 3, '3B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3c', 'apartment-2', 3, '3C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3d', 'apartment-2', 3, '3D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3e', 'apartment-2', 3, '3E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3f', 'apartment-2', 3, '3F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3g', 'apartment-2', 3, '3G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-2-3h', 'apartment-2', 3, '3H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');

-- Apartment 3 - All levels
INSERT INTO plots (plot_id, section, level, plot_number, status, occupant_name, age, cause_of_death, religion, family_name, next_of_kin, contact_number, date_of_interment, notes) VALUES
('apartment-3-1a', 'apartment-3', 1, '1A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-1b', 'apartment-3', 1, '1B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-1c', 'apartment-3', 1, '1C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-1d', 'apartment-3', 1, '1D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-1e', 'apartment-3', 1, '1E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-1f', 'apartment-3', 1, '1F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-1g', 'apartment-3', 1, '1G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-1h', 'apartment-3', 1, '1H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2a', 'apartment-3', 2, '2A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2b', 'apartment-3', 2, '2B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2c', 'apartment-3', 2, '2C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2d', 'apartment-3', 2, '2D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2e', 'apartment-3', 2, '2E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2f', 'apartment-3', 2, '2F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2g', 'apartment-3', 2, '2G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-2h', 'apartment-3', 2, '2H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3a', 'apartment-3', 3, '3A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3b', 'apartment-3', 3, '3B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3c', 'apartment-3', 3, '3C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3d', 'apartment-3', 3, '3D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3e', 'apartment-3', 3, '3E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3f', 'apartment-3', 3, '3F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3g', 'apartment-3', 3, '3G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-3-3h', 'apartment-3', 3, '3H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');

-- Apartment 4 - All levels
INSERT INTO plots (plot_id, section, level, plot_number, status, occupant_name, age, cause_of_death, religion, family_name, next_of_kin, contact_number, date_of_interment, notes) VALUES
('apartment-4-1a', 'apartment-4', 1, '1A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-1b', 'apartment-4', 1, '1B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-1c', 'apartment-4', 1, '1C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-1d', 'apartment-4', 1, '1D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-1e', 'apartment-4', 1, '1E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-1f', 'apartment-4', 1, '1F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-1g', 'apartment-4', 1, '1G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-1h', 'apartment-4', 1, '1H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2a', 'apartment-4', 2, '2A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2b', 'apartment-4', 2, '2B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2c', 'apartment-4', 2, '2C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2d', 'apartment-4', 2, '2D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2e', 'apartment-4', 2, '2E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2f', 'apartment-4', 2, '2F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2g', 'apartment-4', 2, '2G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-2h', 'apartment-4', 2, '2H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3a', 'apartment-4', 3, '3A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3b', 'apartment-4', 3, '3B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3c', 'apartment-4', 3, '3C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3d', 'apartment-4', 3, '3D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3e', 'apartment-4', 3, '3E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3f', 'apartment-4', 3, '3F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3g', 'apartment-4', 3, '3G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-4-3h', 'apartment-4', 3, '3H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');

-- Apartment 5 - All levels
INSERT INTO plots (plot_id, section, level, plot_number, status, occupant_name, age, cause_of_death, religion, family_name, next_of_kin, contact_number, date_of_interment, notes) VALUES
('apartment-5-1a', 'apartment-5', 1, '1A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-1b', 'apartment-5', 1, '1B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-1c', 'apartment-5', 1, '1C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-1d', 'apartment-5', 1, '1D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-1e', 'apartment-5', 1, '1E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-1f', 'apartment-5', 1, '1F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-1g', 'apartment-5', 1, '1G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-1h', 'apartment-5', 1, '1H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2a', 'apartment-5', 2, '2A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2b', 'apartment-5', 2, '2B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2c', 'apartment-5', 2, '2C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2d', 'apartment-5', 2, '2D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2e', 'apartment-5', 2, '2E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2f', 'apartment-5', 2, '2F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2g', 'apartment-5', 2, '2G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-2h', 'apartment-5', 2, '2H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3a', 'apartment-5', 3, '3A', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3b', 'apartment-5', 3, '3B', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3c', 'apartment-5', 3, '3C', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3d', 'apartment-5', 3, '3D', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3e', 'apartment-5', 3, '3E', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3f', 'apartment-5', 3, '3F', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3g', 'apartment-5', 3, '3G', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''),
('apartment-5-3h', 'apartment-5', 3, '3H', 'available', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');



